name: Github call Intersight Orchestrator Workflow - Developer Enviroment
on:
  push:
  branches: 
      - development
 


 jobs:
  runs-on: ubuntu-latest
  steps:
      uses: fjogeleit/http-request-action@master
      
